[json_settings]
# Здесь вы можете указать файлы, которые будут использоваться утилитой как правила
rules_regex=rules/default_regex.json
rules_ignore=rules/default_ignore.json
default_result_filename=result.json
ast_keywords=rules/ast_keywords.json
criticality_paths=rules/criticality_paths.json